name    'piersharding-r'
version '0.0.1'
source 'UNKNOWN'
author 'Piers Harding'
license 'Apache License, Version 2.0'
summary 'Install and manage R and its packages'
description 'Install and manage R; provides a defined type to install packages'
project_page 'https://github.com/piersharding/puppet-r'
